### ISSUE TITLE
Some tiles are missing, invalid, or ugly

### ISSUE THREAD

**Issue by volgar1x** [cabaf-lehavre/fjorde#17]
Please comment below of any missing, invalid, or ugly tiles.

**Comment by volgar1x** [comment]
PPMPPP has the M displayed as a S

**Comment by volgar1x** [comment]
PSPMMM won't rotate

**Comment by Tartusi** [comment]
PPMMPS ugly

**Comment by ScarletArnett** [comment]
If i get the time, i'll remake all ugly tiles don't worry

**Comment by Tartusi** [comment]
PMMMPS
PSPMMM
ugly

**Comment by ScarletArnett** [comment]
" PPMPPP has the M displayed as a S " 
Fixed for me wtf?

**Comment by volgar1x** [comment]
PPMMPP is kinda ugly, it really is visible when rotating its peers.

**Comment by volgar1x** [comment]
PPPPPS has a slightly darker blue

**Comment by ScarletArnett** [comment]
i'll remake all ugly tiles after 10pm+

**Comment by ScarletArnett** [comment]
Fixed
