### ISSUE TITLE
Ask a player its name 

### ISSUE THREAD

**Issue by volgar1x** [cabaf-lehavre/fjorde#21]

**Comment by ScarletArnett** [comment]
I was thinking about just put it as a regular name like Conan, Barbarius etc

**Comment by volgar1x** [comment]
Do you mean randomly choose a name from a finite list? In that case, how do that differ from the first proposal?

**Comment by ScarletArnett** [comment]
No just put it in the code like we did for Mickael, fucking bay

**Comment by volgar1x** [comment]
Are you suggesting to _not_ do anything? :laughing:

**Comment by ScarletArnett** [comment]
Yeah, no point to ask their name because they suck lol

**Comment by volgar1x** [comment]
![Well that escalated quickly](http://img1.wikia.nocookie.net/__cb20130820154201/theevilliouschronicles/images/thumb/8/8a/Meme-well-that-escalated-quickly.jpg/500px-Meme-well-that-escalated-quickly.jpg)

**Comment by ScarletArnett** [comment]
I'm doing it ! Trying but hum, doesn't go as predicted http://puu.sh/ezaxF/54fff4b673.png LOL

**Comment by volgar1x** [comment]
Or you could have just created a new JFrame instead :smile:

**Comment by ScarletArnett** [comment]
I AM TRYING
